### ISSUE TITLE
Emoji One Color font available

### ISSUE THREAD

**Issue by eosrei** [gentakojima/emojione-picker-ubuntu#9]
I've got a potential update for your readme question ["When I paste all/some icons, they are shown as ugly boxes. I want my money back!"](https://github.com/gentakojima/emojione-picker-ubuntu#when-i-paste-allsome-icons-they-are-shown-as-ugly-boxes-i-want-my-money-back). I made: https://github.com/eosrei/emojione-color-font It uses the emojione graphics to display full color emoji in Firefox/Thunderbird using the SVGinOT color font standard, plus I generated b&w glyphs for fallback use in other browsers/applications.

FYI: Emojione Picker works perfectly in MATE using your PPA 😍 Thanks!

**Comment by gentakojima** [comment]
Thank you very much for this suggestion. I think your proposal is very interesting and I'm looking forward seeing this working! 👍

However, I can't follow your instructions. I'm stuck at step 3: *Double click the ttf file to open it in Font Viewer*. I can't find any *ttf* file. Maybe you are missing it?

**Comment by eosrei** [comment]
The only explanation I have is you downloaded the source code and not the binary file. The binary is on the release page: https://github.com/eosrei/emojione-color-font/releases The direct link is: https://github.com/eosrei/emojione-color-font/releases/download/v1.0-beta/EmojiOneColor-SVGinOT.ttf.zip

If that's the solution, I'd be really happy to hear how I can make this more clear (docs? links?) I don't want to link specifically to the binary, but since everyone expects to download source code from github, I may have to.

**Comment by gentakojima** [comment]
Wow, I can't believe this is working, it's amazing! 👍 I tried these instructions (maybe not the same, but they looked the same to me) some time ago and it didn't work.

Yep, the instructions could certainly be better. Specifically the download part. Also, the part that says «can be installed and set as the default Emoji font system wide» doesn't correspond to the instructions given, which will only install the emojis for the current user. 

To install the emojis system-wide, you must install the fonts with other mechanisms (i'd take a look into any other font package) and set the config inside a file in /etc/fonts/conf.d instead of the given directory.

Maybe change that text to «can be installed and set as the default Emoji font for the current user» could be easier.

Even if you don't include the font in your repository, you might include a installer script which downloads the font and does these changes automatically. 

I'm interested on making a Debian package that automate this and upload the package it into a PPA later. Once I get it working, I can make a pull request into your repo to include the package specification here and upload the package into a PPA (wether yours or mine, I don't care).

**Comment by eosrei** [comment]
>Wow, I can't believe this is working, it's amazing! 

Awesome!

> can be installed and set as the default Emoji font system wide

Good point, I forgot to update that. You *can* make it system-wide, but I'm not covering that in the instructions. I'll fix that.

> Even if you don't include the font in your repository, you might include a installer script which downloads the font and does these changes automatically. 

That could work, but then people need to download the installer :laughing: which can cause the same problem. Hmm.. I could package a install.sh in the zip file though. I'll be making a Linux-specific version shortly due to: https://github.com/eosrei/emojione-color-font/issues/2

> I'm interested on making a Debian package that automate this and upload the package it into a PPA later

Yes! I plan to make a PPA, but must get the last two breaking issues worked out. The above and this: https://github.com/eosrei/emojione-color-font/issues/3

**Comment by gentakojima** [comment]
Thank you for all this info! This is an amazing work!

I'm taking a look into this when I have the time, maybe I can lend a hand, but I'll focus on the picker by now. It seems like you have everything under control.

I'll definitely update the instructions in the README. I'll leave this opened until I do. 🐨

**Comment by gentakojima** [comment]
Fixed now, thanks!

**Comment by eosrei** [comment]
Great! Absolutely let me know if you see any thing to fix or make better. I'll update the Linux instructions soonish.
